# Generated by Django 5.2.4 on 2026-03-21 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
            },
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Ex: Developpeur Web Full Stack', max_length=255)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Taux horaire en HTG', max_digits=10)),
                ('availability', models.CharField(choices=[('available', 'Disponible'), ('busy', 'Occupe'), ('unavailable', 'Indisponible')], default='available', max_length=20)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('portfolio_url', models.URLField(blank=True)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('completed_jobs', models.PositiveIntegerField(default=0)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('languages', models.ManyToManyField(blank=True, to='accounts.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer', to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('url', models.URLField(blank=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='freelancers.freelancerprofile')),
                ('skills', models.ManyToManyField(blank=True, to='freelancers.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreelancerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Debutant'), ('intermediate', 'Intermediaire'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancers.freelancerprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancers.skill')),
            ],
            options={
                'unique_together': {('freelancer', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, through='freelancers.FreelancerSkill', to='freelancers.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='freelancers.skillcategory'),
        ),
    ]
