# Generated by Django 5.2.4 on 2026-03-21 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        ('freelancers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('budget_type', models.CharField(choices=[('fixed', 'Prix fixe'), ('hourly', 'Taux horaire')], default='fixed', max_length=10)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.CharField(blank=True, choices=[('less_week', "Moins d'une semaine"), ('one_two_weeks', '1-2 semaines'), ('two_four_weeks', '2-4 semaines'), ('one_three_months', '1-3 mois'), ('three_six_months', '3-6 mois'), ('more_six_months', 'Plus de 6 mois')], max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('open', 'Ouvert'), ('in_progress', 'En cours'), ('completed', 'Termine'), ('cancelled', 'Annule')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Prive'), ('invite_only', 'Sur invitation')], default='public', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.userprofile')),
                ('skills_required', models.ManyToManyField(blank=True, related_name='projects', to='freelancers.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_letter', models.TextField()),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_duration', models.PositiveIntegerField(help_text='Duree estimee en jours')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepte'), ('rejected', 'Rejete'), ('withdrawn', 'Retire')], default='pending', max_length=20)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='freelancers.freelancerprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'freelancer')},
            },
        ),
    ]
